# Numerical validation of EpiNow2.jl against R's EpiNow2
#
# Compares posterior summary statistics (means, medians, CIs) between
# Julia and R implementations. Both use different samplers (Turing NUTS
# vs Stan NUTS) so we expect qualitative agreement, not exact matches.
#
# Run: julia --project test/validate_against_r.jl
# Requires: test/reference/ directory generated by test/generate_r_reference.R

using Test
using EpiNow2
using DataFrames
using Dates
using Distributions
using CSV
using Statistics

const REFDIR = joinpath(@__DIR__, "reference")

# ── Helpers ──────────────────────────────────────────────────────────────

"""Load R reference data and return the input DataFrame + reference summaries."""
function load_reference(test_name)
    input = CSV.read(joinpath(REFDIR, "input_data.csv"), DataFrame)
    input.date = Date.(input.date)

    rt = CSV.read(joinpath(REFDIR, "$(test_name)_rt.csv"), DataFrame)
    infections = CSV.read(joinpath(REFDIR, "$(test_name)_infections.csv"), DataFrame)

    # Include all estimate types, exclude forecast
    rt = filter(r -> r.type != "forecast", rt)
    infections = filter(r -> r.type != "forecast", infections)

    (input=input, rt=rt, infections=infections)
end

"""
    compare_summaries(jl_df, r_df, variable; rtol=0.3)

Compare Julia and R posterior summaries. Uses relative tolerance on medians.
Returns a NamedTuple with comparison metrics.
"""
function compare_summaries(jl_df, r_df, variable; rtol=0.3)
    # Align by date
    n = min(nrow(jl_df), nrow(r_df))
    jl = jl_df[1:n, :]
    r = r_df[1:n, :]

    jl_med = jl.median
    r_med = r.median

    # Correlation
    corr = cor(jl_med, r_med)

    # Relative error (median across time points)
    rel_errors = abs.(jl_med .- r_med) ./ max.(abs.(r_med), 1e-6)
    median_rel_error = median(rel_errors)
    max_rel_error = maximum(rel_errors)

    # Check CIs overlap: R's 90% CI should contain Julia's median most of the time
    r_contains_jl = sum(
        (jl_med .>= r.lower_90) .& (jl_med .<= r.upper_90)
    ) / n

    # Julia's 90% CI should contain R's median most of the time
    jl_contains_r = sum(
        (r_med .>= jl.lower_90) .& (r_med .<= jl.upper_90)
    ) / n

    (
        variable=variable,
        n_times=n,
        correlation=corr,
        median_rel_error=median_rel_error,
        max_rel_error=max_rel_error,
        r_ci_contains_jl=r_contains_jl,
        jl_ci_contains_r=jl_contains_r
    )
end

# ── Run Julia models matching the R reference configurations ─────────────

function run_julia_test1(data)
    estimate_infections(
        data;
        generation_time = gt_opts(Dirac(1.0)),
        delays = delay_opts(Dirac(0.0)),
        obs = obs_opts(week_effect=false),
        rt = rt_opts(),
        gp = gp_opts(basis_prop=0.2, boundary_scale=1.5),
        forecast = forecast_opts(horizon=7),
        inference = inference_opts(
            samples=1000, warmup=500, chains=1, seed=42, progress=false
        ),
        verbose=false
    )
end

function run_julia_test2(data)
    estimate_infections(
        data;
        generation_time = gt_opts(LogNormal(1.6, 0.5)),
        delays = delay_opts(Dirac(0.0)),
        obs = obs_opts(week_effect=false),
        rt = rt_opts(),
        gp = gp_opts(basis_prop=0.2, boundary_scale=1.5),
        forecast = forecast_opts(horizon=7),
        inference = inference_opts(
            samples=1000, warmup=500, chains=1, seed=42, progress=false
        ),
        verbose=false
    )
end

function run_julia_test3(data)
    estimate_infections(
        data;
        generation_time = gt_opts(LogNormal(1.6, 0.5)),
        delays = delay_opts(LogNormal(0.5, 0.5)),
        obs = obs_opts(week_effect=false),
        rt = rt_opts(),
        gp = gp_opts(basis_prop=0.2, boundary_scale=1.5),
        forecast = forecast_opts(horizon=7),
        inference = inference_opts(
            samples=1000, warmup=500, chains=1, seed=42, progress=false
        ),
        verbose=false
    )
end

function run_julia_test4(data)
    estimate_infections(
        data;
        generation_time = gt_opts(LogNormal(1.6, 0.5)),
        delays = delay_opts(LogNormal(0.5, 0.5)),
        obs = obs_opts(week_effect=true),
        rt = rt_opts(),
        gp = gp_opts(basis_prop=0.2, boundary_scale=1.5),
        forecast = forecast_opts(horizon=7),
        inference = inference_opts(
            samples=1000, warmup=500, chains=1, seed=42, progress=false
        ),
        verbose=false
    )
end

function run_julia_secondary(data)
    estimate_secondary(
        data;
        secondary = secondary_opts(),  # incidence (default), matches R
        delays = delay_opts(discretise(LogNormal(1.6, 0.5); max=14)),
        obs = obs_opts(
            family = poisson,
            week_effect = false,
            scale = truncated(Normal(0.3, 0.1); lower=0.0)
        ),
        inference = inference_opts(
            samples=1000, warmup=500, chains=1, seed=42, progress=false
        ),
        burn_in=14,
        verbose=false
    )
end

function run_julia_truncation(snapshots)
    # max=10 and Normal(1,1) sdlog prior match the R reference configuration.
    trunc_dist = EpiNow2.UncertainDistribution(
        (m, s) -> LogNormal(m, s), [Normal(0.0, 1.0), Normal(1.0, 1.0)], 10.0
    )
    estimate_truncation(
        snapshots;
        truncation = trunc_opts(
            trunc_dist;
            meanlog_prior = Normal(0.0, 1.0),
            sdlog_prior = truncated(Normal(1.0, 1.0); lower=0.0)
        ),
        inference = inference_opts(
            samples=1000, warmup=500, chains=1, seed=42, progress=false
        ),
        verbose=false
    )
end

# ── Main validation ──────────────────────────────────────────────────────

function run_validation()
    if !isdir(REFDIR)
        @warn "Reference directory not found at $REFDIR. " *
              "Run `Rscript test/generate_r_reference.R` first."
        return
    end

    tests = [
        ("test1", "Simplest (Dirac GT, no delay, no week effect)", run_julia_test1),
        ("test2", "With LogNormal generation time", run_julia_test2),
        ("test3", "With GT + reporting delay", run_julia_test3),
        ("test4", "Full model with week effect", run_julia_test4),
    ]

    @testset "Numerical validation against R" begin
        for (name, description, runner) in tests
            ref_rt_path = joinpath(REFDIR, "$(name)_rt.csv")
            if !isfile(ref_rt_path)
                @warn "Skipping $name: reference file not found"
                continue
            end

            println("\n", "="^70)
            println("Validation: $description")
            println("="^70)

            ref = load_reference(name)
            println("Running Julia model...")
            result = runner(ref.input)

            # Compare Rt
            rt_comp = compare_summaries(result.rt, ref.rt, "Rt")
            println("\nRt comparison:")
            println("  Correlation:        $(round(rt_comp.correlation, digits=3))")
            println("  Median rel. error:  $(round(rt_comp.median_rel_error, digits=3))")
            println("  Max rel. error:     $(round(rt_comp.max_rel_error, digits=3))")
            println("  R CI contains Jl:   $(round(rt_comp.r_ci_contains_jl, digits=2))")
            println("  Jl CI contains R:   $(round(rt_comp.jl_ci_contains_r, digits=2))")

            # Compare infections
            inf_comp = compare_summaries(result.infections, ref.infections, "infections")
            println("\nInfections comparison:")
            println("  Correlation:        $(round(inf_comp.correlation, digits=3))")
            println("  Median rel. error:  $(round(inf_comp.median_rel_error, digits=3))")
            println("  Max rel. error:     $(round(inf_comp.max_rel_error, digits=3))")
            println("  R CI contains Jl:   $(round(inf_comp.r_ci_contains_jl, digits=2))")
            println("  Jl CI contains R:   $(round(inf_comp.jl_ci_contains_r, digits=2))")

            @testset "$description" begin
                # Rt: median relative error < 30% (stable across runs)
                @test rt_comp.median_rel_error < 0.3
                # Infections: correlation should be high
                @test inf_comp.correlation > 0.9
                # Infections: median relative error should be reasonable
                @test inf_comp.median_rel_error < 0.5
            end
        end

        # ── estimate_secondary ───────────────────────────────────────────
        sec_input_path = joinpath(REFDIR, "secondary_input.csv")
        sec_pred_path = joinpath(REFDIR, "secondary_predictions.csv")
        if isfile(sec_input_path) && isfile(sec_pred_path)
            println("\n", "="^70)
            println("Validation: estimate_secondary (cases → secondary)")
            println("="^70)

            sec_data = CSV.read(sec_input_path, DataFrame)
            sec_data.date = Date.(sec_data.date)
            r_pred = CSV.read(sec_pred_path, DataFrame)
            r_pred.date = Date.(r_pred.date)

            println("Running Julia estimate_secondary...")
            sec_result = run_julia_secondary(sec_data)

            # R predictions cover only the post-burn-in period; align by date
            r_dates = Set(r_pred.date)
            jl_pred = filter(row -> row.date in r_dates, sec_result.predictions)
            sort!(jl_pred, :date)
            sort!(r_pred, :date)

            sec_comp = compare_summaries(jl_pred, r_pred, "secondary")
            # Both sides are posterior predictive (R's get_predictions and Julia's
            # predictions include observation noise), so credible-interval widths
            # are directly comparable too.
            n = min(nrow(jl_pred), nrow(r_pred))
            jl_w = mean(jl_pred.upper_90[1:n] .- jl_pred.lower_90[1:n])
            r_w = mean(r_pred.upper_90[1:n] .- r_pred.lower_90[1:n])
            ci_width_ratio = jl_w / r_w
            println("\nSecondary (posterior predictive) comparison:")
            println("  Correlation:        $(round(sec_comp.correlation, digits=3))")
            println("  Median rel. error:  $(round(sec_comp.median_rel_error, digits=3))")
            println("  Max rel. error:     $(round(sec_comp.max_rel_error, digits=3))")
            println("  90% CI width ratio: $(round(ci_width_ratio, digits=3)) (Jl/R)")

            @testset "estimate_secondary" begin
                # The expected secondary series tracks scaled+delayed primary,
                # so correlation with R should be very high.
                @test sec_comp.correlation > 0.95
                # Central estimate should match R within a modest tolerance.
                @test sec_comp.median_rel_error < 0.3
                # Posterior-predictive uncertainty should match R: CI widths
                # within 25% of R's (both include observation noise).
                @test 0.75 < ci_width_ratio < 1.25
            end
        else
            @warn "Skipping estimate_secondary: reference files not found"
        end

        # ── estimate_truncation ──────────────────────────────────────────
        trunc_input_path = joinpath(REFDIR, "truncation_input.csv")
        trunc_param_path = joinpath(REFDIR, "truncation_params.csv")
        if isfile(trunc_input_path) && isfile(trunc_param_path)
            println("\n", "="^70)
            println("Validation: estimate_truncation (reporting delay)")
            println("="^70)

            tinp = CSV.read(trunc_input_path, DataFrame)
            tinp.date = Date.(tinp.date)
            snapshots = [
                select(filter(r -> r.snapshot == i, tinp), :date, :confirm)
                for i in sort(unique(tinp.snapshot))
            ]

            r_params = CSV.read(trunc_param_path, DataFrame)
            # truncation[1] = meanlog, truncation[2] = sdlog
            r_meanlog = only(filter(r -> r.variable == "truncation[1]", r_params).mean)
            r_sdlog = only(filter(r -> r.variable == "truncation[2]", r_params).mean)

            println("Running Julia estimate_truncation...")
            tres = run_julia_truncation(snapshots)
            gqs = tres.fit.generated_quantities
            jl_meanlog = mean(g.trunc_meanlog for g in gqs)
            jl_sdlog = mean(g.trunc_sdlog for g in gqs)

            ml_err = abs(jl_meanlog - r_meanlog) / abs(r_meanlog)
            sl_err = abs(jl_sdlog - r_sdlog) / abs(r_sdlog)
            println("\nTruncation distribution comparison:")
            println("  meanlog: Julia $(round(jl_meanlog, digits=3)) vs R $(round(r_meanlog, digits=3)) (rel err $(round(ml_err, digits=3)))")
            println("  sdlog:   Julia $(round(jl_sdlog, digits=3)) vs R $(round(r_sdlog, digits=3)) (rel err $(round(sl_err, digits=3)))")

            @testset "estimate_truncation" begin
                # Julia replicates R's truncation algorithm (latent
                # reconstruction, NegBin obs), so meanlog matches closely.
                @test ml_err < 0.05
                # sdlog sits ~20% above R: the package uses double interval
                # censoring everywhere, whereas R's estimate_truncation uses its
                # cruder Stan discretised_pmf. This is a deliberate divergence
                # (consistent discretisation was preferred over matching R here).
                @test sl_err < 0.25
            end
        else
            @warn "Skipping estimate_truncation: reference files not found"
        end
    end
end

run_validation()
