# Numerical validation of EpiNow2.jl against R's EpiNow2
#
# Compares posterior summary statistics (means, medians, CIs) between
# Julia and R implementations. Both use different samplers (Turing NUTS
# vs Stan NUTS) so we expect qualitative agreement, not exact matches.
#
# Run: julia --project test/validate_against_r.jl
# Requires: test/reference/ directory generated by test/generate_r_reference.R

using Test
using EpiNow2
using DataFrames
using Dates
using Distributions
using CSV
using Statistics

const REFDIR = joinpath(@__DIR__, "reference")

# ── Helpers ──────────────────────────────────────────────────────────────

"""Load R reference data and return the input DataFrame + reference summaries."""
function load_reference(test_name)
    input = CSV.read(joinpath(REFDIR, "input_data.csv"), DataFrame)
    input.date = Date.(input.date)

    rt = CSV.read(joinpath(REFDIR, "$(test_name)_rt.csv"), DataFrame)
    infections = CSV.read(joinpath(REFDIR, "$(test_name)_infections.csv"), DataFrame)

    # Include all estimate types, exclude forecast
    rt = filter(r -> r.type != "forecast", rt)
    infections = filter(r -> r.type != "forecast", infections)

    (input=input, rt=rt, infections=infections)
end

"""
    compare_summaries(jl_df, r_df, variable; rtol=0.3)

Compare Julia and R posterior summaries. Uses relative tolerance on medians.
Returns a NamedTuple with comparison metrics.
"""
function compare_summaries(jl_df, r_df, variable; rtol=0.3)
    # Align by date
    n = min(nrow(jl_df), nrow(r_df))
    jl = jl_df[1:n, :]
    r = r_df[1:n, :]

    jl_med = jl.median
    r_med = r.median

    # Correlation
    corr = cor(jl_med, r_med)

    # Relative error (median across time points)
    rel_errors = abs.(jl_med .- r_med) ./ max.(abs.(r_med), 1e-6)
    median_rel_error = median(rel_errors)
    max_rel_error = maximum(rel_errors)

    # Check CIs overlap: R's 90% CI should contain Julia's median most of the time
    r_contains_jl = sum(
        (jl_med .>= r.lower_90) .& (jl_med .<= r.upper_90)
    ) / n

    # Julia's 90% CI should contain R's median most of the time
    jl_contains_r = sum(
        (r_med .>= jl.lower_90) .& (r_med .<= jl.upper_90)
    ) / n

    (
        variable=variable,
        n_times=n,
        correlation=corr,
        median_rel_error=median_rel_error,
        max_rel_error=max_rel_error,
        r_ci_contains_jl=r_contains_jl,
        jl_ci_contains_r=jl_contains_r
    )
end

# ── Run Julia models matching the R reference configurations ─────────────

function run_julia_test1(data)
    estimate_infections(
        data;
        generation_time = gt_opts(Dirac(1.0)),
        delays = delay_opts(Dirac(0.0)),
        obs = obs_opts(week_effect=false),
        rt = rt_opts(),
        gp = gp_opts(basis_prop=0.2, boundary_scale=1.5),
        forecast = forecast_opts(horizon=7),
        inference = inference_opts(
            samples=1000, warmup=500, chains=1, seed=42, progress=false
        ),
        verbose=false
    )
end

function run_julia_test2(data)
    estimate_infections(
        data;
        generation_time = gt_opts(LogNormal(1.6, 0.5)),
        delays = delay_opts(Dirac(0.0)),
        obs = obs_opts(week_effect=false),
        rt = rt_opts(),
        gp = gp_opts(basis_prop=0.2, boundary_scale=1.5),
        forecast = forecast_opts(horizon=7),
        inference = inference_opts(
            samples=1000, warmup=500, chains=1, seed=42, progress=false
        ),
        verbose=false
    )
end

function run_julia_test3(data)
    estimate_infections(
        data;
        generation_time = gt_opts(LogNormal(1.6, 0.5)),
        delays = delay_opts(LogNormal(0.5, 0.5)),
        obs = obs_opts(week_effect=false),
        rt = rt_opts(),
        gp = gp_opts(basis_prop=0.2, boundary_scale=1.5),
        forecast = forecast_opts(horizon=7),
        inference = inference_opts(
            samples=1000, warmup=500, chains=1, seed=42, progress=false
        ),
        verbose=false
    )
end

function run_julia_test4(data)
    estimate_infections(
        data;
        generation_time = gt_opts(LogNormal(1.6, 0.5)),
        delays = delay_opts(LogNormal(0.5, 0.5)),
        obs = obs_opts(week_effect=true),
        rt = rt_opts(),
        gp = gp_opts(basis_prop=0.2, boundary_scale=1.5),
        forecast = forecast_opts(horizon=7),
        inference = inference_opts(
            samples=1000, warmup=500, chains=1, seed=42, progress=false
        ),
        verbose=false
    )
end

# ── Main validation ──────────────────────────────────────────────────────

function run_validation()
    if !isdir(REFDIR)
        @warn "Reference directory not found at $REFDIR. " *
              "Run `Rscript test/generate_r_reference.R` first."
        return
    end

    tests = [
        ("test1", "Simplest (Dirac GT, no delay, no week effect)", run_julia_test1),
        ("test2", "With LogNormal generation time", run_julia_test2),
        ("test3", "With GT + reporting delay", run_julia_test3),
        ("test4", "Full model with week effect", run_julia_test4),
    ]

    @testset "Numerical validation against R" begin
        for (name, description, runner) in tests
            ref_rt_path = joinpath(REFDIR, "$(name)_rt.csv")
            if !isfile(ref_rt_path)
                @warn "Skipping $name: reference file not found"
                continue
            end

            println("\n", "="^70)
            println("Validation: $description")
            println("="^70)

            ref = load_reference(name)
            println("Running Julia model...")
            result = runner(ref.input)

            # Compare Rt
            rt_comp = compare_summaries(result.rt, ref.rt, "Rt")
            println("\nRt comparison:")
            println("  Correlation:        $(round(rt_comp.correlation, digits=3))")
            println("  Median rel. error:  $(round(rt_comp.median_rel_error, digits=3))")
            println("  Max rel. error:     $(round(rt_comp.max_rel_error, digits=3))")
            println("  R CI contains Jl:   $(round(rt_comp.r_ci_contains_jl, digits=2))")
            println("  Jl CI contains R:   $(round(rt_comp.jl_ci_contains_r, digits=2))")

            # Compare infections
            inf_comp = compare_summaries(result.infections, ref.infections, "infections")
            println("\nInfections comparison:")
            println("  Correlation:        $(round(inf_comp.correlation, digits=3))")
            println("  Median rel. error:  $(round(inf_comp.median_rel_error, digits=3))")
            println("  Max rel. error:     $(round(inf_comp.max_rel_error, digits=3))")
            println("  R CI contains Jl:   $(round(inf_comp.r_ci_contains_jl, digits=2))")
            println("  Jl CI contains R:   $(round(inf_comp.jl_ci_contains_r, digits=2))")

            @testset "$description" begin
                # Rt: median relative error < 30% (stable across runs)
                @test rt_comp.median_rel_error < 0.3
                # Infections: correlation should be high
                @test inf_comp.correlation > 0.9
                # Infections: median relative error should be reasonable
                @test inf_comp.median_rel_error < 0.5
            end
        end
    end
end

run_validation()
